### ISSUE TITLE
is schema-mysql.sql file missing?

### ISSUE THREAD

**Issue by sridhar1982** [mminella/RecommendationEngine#1]
I have been watching your demo on the recommendationEngine. It is amazing and you go into all the details making the presentation very clear unlike many others!

This is a **question**
I am browsing through the code. I noticed that in
`https://github.com/mminella/RecommendationEngine/blob/master/spring-overflow-spring/src/main/resources/application.properties`
you have defined
`spring.datasource.schema=schema-mysql.sql`
but where is this schema coming from? I do not see any such file in this repo or may be I am missing something in this context?

Thanks

**Comment by mminella** [comment]
It's in the database import module and can be found here: https://github.com/mminella/RecommendationEngine/blob/master/database-import/src/main/resources/schema-mysql.sql
